### PR TITLE
feat: make this library *-testing-library conform

### LINKED ISSUE #4: Bring more in line with the rest of the testing-library family?
Hi there! 👋

I noticed that the API that this exposes makes it a bit different from the rest of the *-testing-library projects we have. Any interest in reworking it to be more familiar for folks used to the *-testing-library projects?

### PR DESCRIPTION
**Pull request by timdeschryver**
This introduces also a couple of breaking changes:

- `createComponent` is renamed to `render` - should be possible to provide a schematic for this to make the transition easier
- `getFromTestBed` is removed, use `TestBed.get` directly instead
- upgrades to dom-testing-library, which had some [breaking changes](https://github.com/testing-library/dom-testing-library/releases/tag/v4.0.0)
- signature changes, properties are passed through via `RenderOptions` as `componentProperties`

Closes #4

### CODE REVIEW

**Comment by kentcdodds** [comment]
This looks really awesome! You may consider moving the bulk of the documentation over to https://testing-library.com/angular as well 👍

**Comment by timdeschryver** [comment]
fyi @kentcdodds , I will cut a release with these changes on Monday.

I also trimmed down the [README](https://github.com/angular-extensions/testing-library/blob/testing-library-conform/README.md) (a copy paste from the svelte library) and will start updating the docs on the docs repository. I noticed all of the *-testing-libraries are using an animal as logo, I picked up the 🦔 if that's OK 😃.

**Comment by kentcdodds** [comment]
Love that emoji. It's perfect 🦔

**Comment by IanIsFluent** [comment]
I notice that this PR mentions a schematic 'to make the transition easier' - has any work been done on this?

Thanks! 🙏

**Pull request merged**
